name: Tweet on Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the new version number'
        required: true

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-actions/tweet@v1.0.0
        with:
          text: "🚀 New version released: ${{ github.event.inputs.version }}! Check it out on GitHub. #Release #OpenSource"
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
